# Generated by Django 4.1.5 on 2023-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='nik@gmail.com', max_length=254),
        ),
    ]
